_wandb:
    value:
        cli_version: 0.25.0
        e:
            zug3sraaeqgiffbfc8vt75gp3ks7av80:
                args:
                    - --dataset
                    - fashion_mnist
                    - --epochs
                    - "20"
                    - --optimizer
                    - rmsprop
                    - --learning_rate
                    - "0.001"
                    - --num_layers
                    - "3"
                    - --hidden_size
                    - "128"
                    - "128"
                    - "64"
                    - --activation
                    - relu
                    - --weight_init
                    - xavier
                    - --wandb_project
                    - assignment_1
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1000186310656"
                        used: "810979483648"
                email: ma25m011@smail.iitm.ac.in
                executable: C:\Users\Rickotte\AppData\Local\Programs\Python\Python313\python.exe
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-3ca8a477-e41d-a640-a258-7723914bcef3
                host: Rickotte
                memory:
                    total: "33409622016"
                os: Windows-11-10.0.26200-SP0
                program: E:\Books\Sem 2\Deep learning\ma25m011_assignment1\src\train.py
                python: CPython 3.13.7
                root: E:\Books\Sem 2\Deep learning\ma25m011_assignment1
                startedAt: "2026-03-10T14:30:28.768683Z"
                writerId: zug3sraaeqgiffbfc8vt75gp3ks7av80
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
config_save_path:
    value: E:\Books\Sem 2\Deep learning\ma25m011_assignment1\src\best_config.json
dataset:
    value: fashion_mnist
epochs:
    value: 20
hidden_size:
    value:
        - 128
        - 128
        - 64
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
model_save_path:
    value: E:\Books\Sem 2\Deep learning\ma25m011_assignment1\src\best_model.npy
no_wandb:
    value: false
num_layers:
    value: 3
optimizer:
    value: rmsprop
wandb_entity:
    value: null
wandb_project:
    value: assignment_1
weight_decay:
    value: 0
weight_init:
    value: xavier
